# Numpy Tutorial

## Import the Numpy Library

In [2]:
import numpy as np

### Create a Numpy Array

In [11]:
myArr = np.array([2, 3, 4, 5])

In [12]:
myArr

array([2, 3, 4, 5])

### Create an array that contains 8 bit integers only

***If you want more bits for your integer, just change the number from 8 to whatever you want like 32, 64 etc.***

In [7]:
myArr = np.array([2, 3, 4, 5], np.int8)

In [8]:
myArr

array([2, 3, 4, 5], dtype=int8)

### Create a Two Dimensional Array using numpy

In [13]:
my2DArray = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [14]:
my2DArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Access elements from the numpy array

In [15]:
print(my2DArray[0, 1])

2


### Get the information about your array

In [19]:
my2DArray.shape

(3, 3)

### Get the datatype

In [21]:
my2DArray.dtype

dtype('int32')